import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

// export const products = [
//   {
//     _id: uuid(),
//     title: "You Can WIN",
//     author: "Shiv Khera",
//     price: "5000",
//     categoryName: "non-fiction",
//   },
//   {
//     _id: uuid(),
//     title: "You are Winner",
//     author: "Junaid Qureshi",
//     price: "3000",
//     categoryName: "horror",
//   },
//   {
//     _id: uuid(),
//     title: "Think and Grow Rich",
//     author: "Shiv Khera",
//     price: "1000",
//     categoryName: "fiction",
//   },
// ];


export const products = [
  {
    _id: uuid(),
    image:
      'https://res.cloudinary.com/ddqytua2y/image/upload/v1685643735/E-commerce-assets/PUMA-Motorsport-Men-Brand-Printed-Hooded-Ferrari-Race-S-1_i6cvsl.avif',
    category: 'Men',
    rating: '4.2',
    size: 'L',
    description: 'PUMA Motorsport - Men Brand Logo Printed Hooded Ferrari Race SDS Sweatshirt',
    title: 'Hooded Sweatshirt',
    trending: true,
    original_price: '5199',
    price: '2719',
    delivery_time: '9',
    reviews: '1.9k',
    in_stock: true,
  },
  {
    _id: uuid(),
    title: 'T-shirt & Shorts',
    original_price: '1599',
    description: 'Nap Chief - Kids Mickey Mouse Printed Pure Cotton T-shirt with Shorts',
    price: '1000',
    rating: '4.6',
    size: 'M',
    image:
      'https://res.cloudinary.com/ddqytua2y/image/upload/v1685648138/E-commerce-assets/861cb22b-3e51-4691-b8ca-0a4ca60d49781680258881644NapChiefUnisexKidsClothingSet1_h2vset.jpg',
    category: 'Kids',
    trending: true,
    reviews: '1.5k',
    in_stock: true,
    delivery_time: '11',
  },
  {
    _id: uuid(),
    image:
      'https://res.cloudinary.com/ddqytua2y/image/upload/v1685644551/E-commerce-assets/USPolo-sleeveless_c104zh.webp',
    category: 'Men',
    rating: '3.8',
    size: 'S',
    description: 'U.S. Polo Assn. - Men Blue & Black Brand Printed Cotton Lounge Tank T-shirt',
    title: 'Cotton Tank T-shirt',
    trending: false,
    original_price: '699',
    price: '519',
    delivery_time: '6',
    reviews: '2.4k',
    in_stock: true,
  },
  {
    _id: uuid(),
    image:
      'https://res.cloudinary.com/ddqytua2y/image/upload/v1685644762/E-commerce-assets/Anouk-Women-Kurta-Sets-2731632810204748-7_scfnsh.webp',
    category: 'Women',
    rating: '4.3',
    size: 'L',
    description:
      'Alena - Women Off-White & Black Printed Kurta with Palazzos & Dupatta',
    title: 'Printed Kurta',
    trending: true,
    original_price: '2999',
    price: '1499',
    delivery_time: '8',
    reviews: '605',
    in_stock: false,
  },
  {
    _id: uuid(),
    image:
      'https://res.cloudinary.com/ddqytua2y/image/upload/v1685645210/E-commerce-assets/KETCHMenWhiteSlimFitTartanChecksCheckedCasualShirt1_tu7rmp.webp',
    category: 'Men',
    rating: '3.8',
    size: 'XXL',
    description: 'KETCH - Men White Slim Fit Tartan Checked Casual Shirt',
    title: 'Casual Shirt',
    trending: true,
    original_price: '899',
    price: '684',
    delivery_time: '1',
    reviews: '2.5k',
    in_stock: true,
  },
  {
    _id: uuid(),
    title: 'Layered Satin Dress',
    original_price: '1399',
    description: 'Pink Chink - Navy Blue & Pink Colourblocked Layered Satin Dress',
    price: '2699',
    rating: '4.1',
    size: 'S',
    image:
      'https://res.cloudinary.com/ddqytua2y/image/upload/v1685645346/E-commerce-assets/9d1cf955-9da9-43d7-b8ff-0b46639a971b1639372851000PinkChickNavyBlueColourblockedLayeredSatinDress4_pmjtp0.jpg',
    category: 'Kids',
    trending: true,
    reviews: '1.5k',
    in_stock: false,
    delivery_time: '7',
  },
  {
    _id: uuid(),
    image:
      'https://res.cloudinary.com/ddqytua2y/image/upload/v1685645534/E-commerce-assets/27bdac69-9868-4ca4-a4b0-472eb4e5b4131652692614657-GERUA-Women-Kurta-Sets-2311652692613816-1_chlsma.jpg',
    category: 'Women',
    rating: '4.3',
    size: 'L',
    description:
      'Gerua - Women Black Ethnic Motifs Printed Gotta Patti Kurta with Trousers',
    title: 'Printed Gotta Patti Kurta',
    trending: true,
    original_price: '759',
    price: '1499',
    delivery_time: '2',
    reviews: '205',
    in_stock: true,
  },
  {
    _id: uuid(),
    image:
      'https://assets.myntassets.com/dpr_2,q_60,w_210,c_limit,fl_progressive/assets/images/20479472/2022/11/15/18da63c9-5acf-4601-ab65-99f0373927fb1668497111915-Allen-Solly-Sport-Men-Sweatshirts-4091668497111291-1.jpg',
    category: 'Men',
    rating: '4.3',
    size: 'M',
    description:
      'Allen Solly - Men Blue Solid Hooded Sweatshirt',
    title: 'Hooded Sweatshirt',
    trending: false,
    original_price: '1999',
    price: '994',
    delivery_time: '5',
    reviews: '4k',
    in_stock: true,
  },
  {
    _id: uuid(),
    image:
      'https://res.cloudinary.com/ddqytua2y/image/upload/v1685648003/E-commerce-assets/9635ee97-6754-45b4-bc4f-01f5996bc97e1638435535022-plusS-Women-Dresses-5411638435534506-1_eh4ezb.jpg',
    category: 'Women',
    rating: '4.5',
    size: 'L',
    description: 'PlusS - Women Maroon Animal Print A-Line Dress',
    title: 'A-Line Dress',
    trending: false,
    original_price: '1398',
    price: '647',
    delivery_time: '4',
    reviews: '7.9K',
    in_stock: true,
  },
  {
    _id: uuid(),
    title: 'Pure Cotton Casual Shirt',
    original_price: '1200',
    description:
      'HERE&NOW - Boys Printed Pure Cotton Casual Shirt',
    price: '499',
    rating: '3.5',
    size: 'M',
    image:
      'https://res.cloudinary.com/ddqytua2y/image/upload/v1685644304/E-commerce-assets/HERENOW-Boys-Printed-Pure-Cotton-Casual-Shirt-24216854420848-1_ziprsu.avif',
    category: 'Kids',
    trending: true,
    reviews: '1.5k',
    in_stock: true,
    delivery_time: '3',
  },
  {
    _id: uuid(),
    image:
      'https://res.cloudinary.com/ddqytua2y/image/upload/v1685648391/E-commerce-assets/d746fa66-b31c-4efb-bf37-94a048c514691663313922382-WROGN-Men-Tshirts-2591663313921843-1_oez6fo.jpg',
    category: 'Men',
    rating: '4.5',
    size: 'M',
    description: 'WROGN - Men Red Brand Logo Pure Cotton Slim Fit T-shirt',
    title: 'Slim Fit T-shirt',
    trending: false,
    original_price: '1499',
    price: '974',
    delivery_time: '3',
    reviews: '3k',
    in_stock: true,
  },
  {
    _id: uuid(),
    image:
      'https://res.cloudinary.com/ddqytua2y/image/upload/v1685648526/E-commerce-assets/d420d176-9255-4639-a612-2dcbe05a95a41670563973742SochMustardPinkEmbroideredPureSilkUnstitchedDressMaterial1_aynnuk.jpg',
    category: 'Women',
    rating: '4.2',
    size: 'S',
    description: 'Soch - Mustard & Pink Embroidered Pure Silk Unstitched Dress Material',
    title: 'Pure Silk Unstitched Dress',
    trending: false,
    original_price: '4298',
    price: '2498',
    delivery_time: '4',
    reviews: '200',
    in_stock: true,
  },
  {
    _id: uuid(),
    image:
      'https://res.cloudinary.com/ddqytua2y/image/upload/v1685648717/E-commerce-assets/48a79326-e9a7-430f-b562-3365211dbfff1612851254843TopsVeroModaWomenSweatshirtsVeroModaWomenSweatersVeroModaWom1_xaqsrf.jpg',
    category: 'Women',
    rating: '3.5',
    size: 'S',
    description: 'Vero Moda - Women Black Self Design Sheer Bell Sleeves A-Line Top',
    title: 'Bell Sleeves A-Line Top',
    trending: false,
    original_price: '1998',
    price: '998',
    delivery_time: '4',
    reviews: '200',
    in_stock: true,
  },
  {
    _id: uuid(),
    title: 'Sporty Jacket',
    description: 'ADIDAS Originals - Men Green FIREBIRD TRACK Sporty Jacket',
    original_price: '3999',
    price: '2604',
    rating: '4',
    size: 'M',
    image:
      'https://res.cloudinary.com/ddqytua2y/image/upload/v1685648819/E-commerce-assets/92c9ac79-11ba-4f94-bcdd-75e82990c0c41674639043587ADIDASOriginalsMenGreenFIREBIRDTRACKSportyJacket1_zrm8ji.jpg',
    category: 'Men',
    trending: false,
    delivery_time: '10',
    reviews: '1000',
    in_stock: false,
  },
];